# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "links", :force => true do |t|
    t.column "website_url", :text
    t.column "token",       :string
    t.column "ip_address",  :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  add_index "links", ["token"], :name => "index_links_on_token"

end
